# Generated by Django 3.0.4 on 2020-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=5000)),
                ('product_category', models.CharField(max_length=200)),
                ('product_subcategory', models.CharField(max_length=200)),
                ('product_pub_date', models.DateTimeField()),
                ('product_image', models.ImageField(upload_to='myshop/product_img')),
                ('product_cost', models.IntegerField()),
            ],
        ),
    ]
