# Generated by Django 3.0.4 on 2020-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20200423_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_products', models.CharField(max_length=5000)),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
