# Generated by Django 3.0.4 on 2020-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20200504_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_payment',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_zip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
