# Generated by Django 3.0.4 on 2020-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_auto_20200505_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('customer_phone', models.CharField(default='', max_length=13)),
                ('customer_email', models.CharField(default='', max_length=40)),
                ('customer_orderid', models.CharField(default='', max_length=40)),
                ('customer_issue', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
