# Generated by Django 3.0.4 on 2020-05-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.CharField(default='', max_length=8),
        ),
    ]
